export const levels = [
  "Less is more.",
  "No pain, no gain.",
  "Enough is enough.",
  "Haste makes waste.",
  "Love is blind.",
  "Talk is cheap.",
  "Boys will be boys.",
  "Easy come, easy go.",
  "Fight fire with fire.",
  "No man is an island.",
  "You reap what you sow",
  "Waste not, want not.",
  "Better late than never.",
  "Let bygones be bygones.",
  "Tomorrow never comes.",
  "Do not rock the boat.",
  "Ignorance is bliss.",
  "It takes one to know one.",
  "It takes two to tango.",
  "All roads lead to Rome.",
  "Better safe than sorry.",
  "Big fish eat little fish.",
  "Cheaters never prosper.",
  "Crime does not pay.",
  "Do as I say, not as I do.",
  "Practice what you preach.",
  "Let sleeping dogs lie.",
  "Look before you leap.",
  "Count your blessings.",
  "History repeats itself.",
  "Practice makes perfect.",
  "Still waters run deep.",
  "Dead men tell no tales.",
  "A miss is as good as a mile.",
  "All is well that ends well.",
  "Home is where the heart is.",
  "Money isn't everything.",
  "No rest for the wicked.",
  "A stitch in time saves nine.",
  "Beggars cannot be choosers.",
  "Cold hands, warm heart.",
  "First come, first served.",
  "Great minds think alike.",
  "Like father, like son.",
  "A good man is hard to find.",
  "Another day, another dollar.",
  "Beauty is only skin deep.",
  "Honesty is the best policy.",
  "Life is what you make of it.",
  "Money doesn't grow on trees.",
  "Oil and water don't mix.",
  "Out of sight, out of mind.",
  "You are never too old to learn.",
  "A friend in need is a friend indeed.",
  "A penny saved is a penny earned.",
  "All is fair in love and war.",
  "Strike while the iron is hot.",
  "Barking dogs seldom bite.",
  "Curiosity killed the cat.",
  "The devil is in the details.",
  "Brevity is the soul of wit.",
  "Enough is as good as a feast.",
  "Small strokes fell great oaks.",
  "Variety is the spice of life.",
  "Time and tide wait for no man.",
  "A woman's work is never done.",
  "Feed a cold, starve a fever.",
  "Give credit where credit is due.",
  "In for a penny, in for a pound.",
  "Where there's smoke there's fire.",
  "Worrying never did anyone any good.",
  "Youth is wasted on the young.",
  "A dog is a man's best friend.",
  "A rising tide lifts all boats.",
  "A rolling stone gathers no moss.",
  "A soft answer turns away wrath.",
  "Blood is thicker than water.",
  "Failing to plan is planning to fail.",
  "Finders keepers, losers weepers.",
  "Flattery will get you nowhere.",
  "Penny wise and pound foolish.",
  "Rome wasn't built in a day.",
  "Truth is stranger than fiction.",
  "History is written by the winners.",
  "What goes up must come down.",
  "Where there's a will there's a way.",
  "A watched pot never boils.",
  "Every cloud has a silver lining.",
  "Beware of Greeks bearing gifts.",
  "Laughter is the best medicine.",
  "Many hands make light work.",
  "Opportunity never knocks twice.",
  "Don't switch horses midstream.",
  "Hindsight is always twenty-twenty.",
  "If it is not broken, do not fix it.",
  "The squeaky wheel gets the grease.",
  "Two wrongs don't make a right.",
  "A leopard cannot change its spots.",
  "A picture paints a thousand words.",
  "Birds of a feather flock together.",
  "Don't bite the hand that feeds you.",
  "Don't burn your bridges behind you.",
  "Don't put the cart before the horse.",
  "Good things come to those who wait.",
  "Don't bring a knife to a gunfight.",
  "Empty vessels make the most noise.",
  "Good fences make good neighbors.",
  "If anything can go wrong, it will.",
  "It is better to give than to receive.",
  "The early bird catches the worm.",
  "Necessity is the mother of invention.",
  "The enemy of my enemy is my friend.",
  "Too many cooks spoil the broth.",
  "What can't be cured must be endured.",
  "Actions speak louder than words.",
  "The pen is mightier than the sword.",
  "All good things must come to an end.",
  "First impressions are the most lasting.",
  "If you pay peanuts, you get monkeys.",
  "Many a true word is spoken in jest.",
  "Never judge a book by its cover.",
  "A fool and his money are soon parted.",
  "An apple a day keeps the doctor away.",
  "Beauty is in the eye of the beholder.",
  "The apple never falls far from the tree.",
  "When the cat's away the mice will play.",
  "When the going gets tough the tough get going.",
  "Absence makes the heart grow fonder.",
  "Don't cast your pearls before swine.",
  "Don't look a gift horse in the mouth.",
  "Don't put all your eggs in one basket.",
  "You must learn to crawl before you can walk.",
  "Fish and guests smell after three days.",
  "If life deals you lemons make lemonade.",
  "Nothing is certain but death and taxes.",
  "The bigger they are, the harder they fall.",
  "There's no such thing as a free lunch.",
  "A bird in the hand is worth two in the bush.",
  "A poor workman always blames his tools.",
  "Don't cut off your nose to spite your face.",
  "The love of money is the root of all evil.",
  "There's more than one way to skin a cat.",
  "Do not wash your dirty linen in public.",
  "You can't have your cake and eat it too.",
  "Doubt is the beginning not the end of wisdom.",
  "Imitation is the sincerest form of flattery.",
  "You can't teach an old dog new tricks.",
  "A person is known by the company he keeps.",
  "Hell hath no fury like a woman scorned.",
  "There is no use crying over spilled milk.",
  "The hand that rocks the cradle rules the world.",
  "Two's company, three's a crowd.",
  "A chain is only as strong as its weakest link.",
  "All work and no play makes Jack a dull boy.",
  "Behind every great man there's a great woman.",
  "Do not cross the bridge until you come to it.",
  "He who lives by the sword shall die by the sword.",
  "Do unto others as you would have them do to you.",
  "If a job is worth doing it is worth doing well.",
  "An ounce of prevention is worth a pound of cure.",
  "Don't throw the baby out with the bath water.",
  "If you want something done well, you have to do it yourself.",
  "Lightning never strikes twice in the same place.",
  "That which does not kill us makes us stronger.",
  "You can't make an omelette without breaking eggs.",
  "The way to a man's heart is through his stomach.",
  "There are none so blind as those that will not see.",
  "A man who is his own lawyer has a fool for a client.",
  "Better to light a candle than to curse the darkness.",
  "Don't count your chickens before they are hatched.",
  "Give a man enough rope and he will hang himself.",
  "Work expands so as to fill the time available.",
  "A place for everything and everything in its place.",
  "Better to have loved and lost than never to have loved at all.",
  "If at first you don't succeed try, try again.",
  "In the kingdom of the blind the one eyed man is king.",
  "If you can't stand the heat, get out of the kitchen.",
  "Everyone wants to go to heaven but nobody wants to die.",
  "Never put off until tomorrow what you can do today.",
  "You catch more flies with honey than with vinegar.",
  "If you lie down with dogs, you will get up with fleas.",
  "No one can make you feel inferior without your consent.",
  "People who live in glass houses shouldn't throw stones.",
  "One half of the world does not know how the other half lives.",
  "The grass is always greener on the other side of the fence.",
  "Those who do not learn from history are doomed to repeat it.",
  "A journey of a thousand miles begins with a single step.",
  "Genius is one percent inspiration, ninety-nine percent perspiration.",
  "If at first you don't succeed, skydiving is not for you.",
  "You can lead a horse to water, but you can't make him drink.",
  "Early to bed and early to rise, makes a man healthy, wealthy and wise.",
  "There is no use locking the stable door after the horse has escaped.",
  "Better to remain silent and be thought a fool than to speak and remove all doubt.",
  "Give a man a fish and feed him for a day; teach him to fish and feed him for a lifetime.",
  "After typing this correctly, I will graduate to the next rank.",
]
